# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Jessie Lin
tagline:          'A Jekyll theme'
description:      '" A goal that doesn’t scare you a little also won’t excite you.<br>
A goal that doesn’t excite you won’t motivate you to work hard. "<br>
- Scott Young'
url:              https://jessie-jingwen-lin.github.io
baseurl:          

paginate:         5

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

sitemap:
  include_posts:
    - "/index.html"

# plugins_dir: [jekyll-sitemap, jekyll-seo-tag]