# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Jessie Lin
tagline:          'A Jekyll theme'
description:      'Looking for data science jobs!'
url:              https://jessie-jingwen-lin.github.io
baseurl:          

paginate:         5

