# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Jessie Lin
tagline:          'A Jekyll theme'
description:      'Looking for data science jobs!'
url:              https://jingwenlin.github.io
baseurl:          

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
